# Edit this file to add dependencies to environment,
# Then run `./lock-environment.sh` to generate reproducible lock files

# !!! If you are developing the website locally use the existing lock files
# for your platform (`conda create --name hackweek --file conda-osx-64.lock`)
name: hackweek
channels:
  - conda-forge
dependencies:
  # Hackweek JupyterHub
  - awscli
  - cartopy
  - dask
  - datashader
  - fsspec
  - geemap
  - gh
  - geopandas
  - geoviews
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - icepyx
  - intake
  - ipyleaflet
  - ipympl
  - jupyterhub-singleuser < 2
  - jupyterlab >= 3
  - jupyter-resource-usage
  - kerchunk
  - matplotlib-base
  - nbgitpuller
  - numpy
  - pandas
  - panel
  - param 
  - pip
  - progressbar2
  - pygeos
  - python = 3.9
  - pystac
  - pystac-client
  - python-graphviz
  - rasterio
  - rioxarray
  - s3fs >= 2022
  - scikit-image
  - scikit-learn
  - scipy
  - sliderule
  - stackstac
  - xarray
  - zarr
  # JupyterBook / Website
  - cookiecutter
  - jinja2 >= 2.11
  - jupyter-book = 0.12
  - pygments >= 2.6.1
  - pymdown-extensions >= 7.1
  - sphinxcontrib-bibtex
  - pip:
    - jinja-markdown==1.210911
    - rio-stac
platforms:
  - linux-64
  - osx-64
