name: Build Without Cache

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure NASA Earthdata Login
      run:
        echo "machine urs.earthdata.nasa.gov login ${{secrets.EARTHDATA_USER}} password ${{secrets.EARTHDATA_PASS}}" > ~/.netrc
        chmod 0600 ~/.netrc

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: false
        publish-to-gh: false
        jb-save: true
