name: Build Without Cache

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: false
        publish-to-gh: false
        jb-save: true
